heutagogy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.landing, name = 'landing'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    # path('logout/', views.logout, name='logout'),
    path('instructor_dashboard/', views.instructor_dashboard, name='instructor_dashboard'),
    path('create_course/', views.create_new_course, name='create_new_course'),
    path('platform/', views.platform, name='platform'),
    path('studio/', views.studio, name='studio'),
]

home/models.py
from django.db import models

# Create your models here.

people/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
import pyrebase
import json
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

firebaseConfig = {
    "apiKey": "AIzaSyAv2Fdg7D52VvYR9TK_H_0z8NiCDj6iQkU",
    "authDomain": "heutagogy-2020.firebaseapp.com",
    "databaseURL": "https://heutagogy-2020.firebaseio.com",
    "projectId": "heutagogy-2020",
    "storageBucket": "heutagogy-2020.appspot.com",
    "messagingSenderId": "772643974559",
    "appId": "1:772643974559:web:d63b880a446d8a70dea1aa",
    "measurementId": "G-X01CP2KNV6"
  }
## For firebase authentication
firebase = pyrebase.initialize_app(firebaseConfig) 
auth = firebase.auth()

## For Firestore database storage
cred = credentials.Certificate('C:\\Users\\suma shreya t v\\Downloads\\heutagogy-2020-6959a4a76c88.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

# Create your views here.
def landing(request):
    return render(request, 'home/landing.html')

def signin(request):
    if request.method=="POST":
        ## Get the form data
        data = request.POST.dict()
        email = data.get('emailaddress')
        password = data.get('password')
        # try:
        user = auth.sign_in_with_email_and_password(email, password)
        uid = user['localId']
        results = db.collection('Teachers').where('uid', '==', uid).get()[0].to_dict()
        return render(request, 'home/instructor_dashboard.html', results)   
        # except:
            # print("Wrong credentials")
            # return render(request, 'home/sign_in.html')
    return render(request, 'home/sign_in.html')

def signup(request):
    if request.method=="POST":
        ## Get the form data
        data = request.POST.dict()
        fullname = data.get('fullname')
        email = data.get('emailaddress')
        password = data.get('password')
        photo_url = data.get('url')
        
        ## Create a new user
        try:
            user = auth.create_user_with_email_and_password(email, password)
        
            ## Get the UID of the user
            uid = user['localId']
        
            ## Push this user's data to the database
            doc_ref = db.collection('Teachers').document(uid)
            doc_ref.set({
                'uid': uid,
                'email': email,
                'fullname': fullname,
                'photo_url': photo_url,
                'courses' : ["C1", "C2", "C3", "C4"],
            })
        
            context = {'email': email, 'fullname': fullname, 'photo_url': photo_url}
            return render(request, 'home/instructor_dashboard.html', context)
        except:
            print("Email already exists")

    return render(request, 'home/sign_up.html')


# def logout(request):
#     auth.signOut()
#     return render(request, 'home/instructor_dashboard.html')

def instructor_dashboard(request):
    user = auth.current_user
    context = {'dashboard_active': 'active', 'user': user}
    return render(request, 'home/instructor_dashboard.html', context)

def create_new_course(request):
    context = {'course_active': 'active'}
    return render(request, 'home/create_new_course.html', context)

def platform(request):
    return render(request, 'platform/platform.html')

def studio(request):
    return render(request, 'studio/studio.html')

people/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	
<!-- Mirrored from gambolthemes.net/html-items/cursus_demo_f12/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 10 Aug 2020 11:34:28 GMT -->
<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">		
		<title>Cursus - Index</title>
		
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'home/images/fav.png' %}">
		
		<!-- Stylesheets -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet'>
		<link href="{% static 'home/vendor/unicons-2.0.1/css/unicons.css' %}" rel='stylesheet'>
		<link href="{% static 'home/css/vertical-responsive-menu.min.css' %}" rel="stylesheet">
		<link href="{% static 'home/css/style.css' %}" rel="stylesheet">
		<link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
        <link href="{% static 'home/css/night-mode.css' %}" rel="stylesheet">
		<link href="{% static 'home/css/vertical-responsive-menu1.min.css' %}" rel="stylesheet">
		<link href="{% static 'home/css/instructor-dashboard.css' %}" rel="stylesheet">
		<link href="{% static 'home/css/instructor-responsive.css' %}" rel="stylesheet">
		
		<!-- Vendor Stylesheets -->
		<link href="{% static 'home/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
		<link href="{% static 'home/vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'home/vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'home/vendor/semantic/semantic.min.css' %}">	
        
        <!-- JS -->
        <script src="{% static 'home/js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'home/js/vertical-responsive-menu.min.js' %}"></script>
        
        <script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'home/vendor/OwlCarousel/owl.carousel.js' %}"></script>
        <script src="{% static 'home/vendor/semantic/semantic.min.js' %}"></script>
        <script src="{% static 'home/js/custom.js' %}"></script>
        <script src="{% static 'home/js/night-mode.js' %}"></script>
		
</head>

home/templates/home/header.html
{% load static %}
{% include 'home/base.html' %}

<header class="header clearfix">
    <button type="button" id="toggleMenu" class="toggle_menu">
      <i class='uil uil-bars'></i>
    </button>
    <button id="collapse_menu" class="collapse_menu">
        <i class="uil uil-bars collapse_menu--icon "></i>
        <span class="collapse_menu--label"></span>
    </button>
    <div class="main_logo" id="logo">
        <a href="{% url 'home:landing' %}"><img src="{% static 'home/images/logo.svg' %}" alt=""></a>
        <a href="{% url 'home:landing' %}"><img class="logo-inverse" src="{% static 'home/images/ct_logo.svg' %}" alt=""></a>
    </div>
    <!-- <div class="top-category">
        <div class="ui compact menu cate-dpdwn">
            <div class="ui simple dropdown item">
                <a href="#" class="option_links p-0" title="categories"><i class="uil uil-apps"></i></a>
                <div class="menu dropdown_category5">
                    <a href="#" class="item channel_item">Development</a>
                    <a href="#" class="item channel_item">Business</a>
                    <a href="#" class="item channel_item">Finance & Accounting</a>
                    <a href="#" class="item channel_item">IT & Software</a>
                    <a href="#" class="item channel_item">Office Productivity</a>
                    <a href="#" class="item channel_item">Personal Development</a>
                    <a href="#" class="item channel_item">Design</a>
                    <a href="#" class="item channel_item">Marketing</a>
                    <a href="#" class="item channel_item">Lifestyle</a>
                    <a href="#" class="item channel_item">Photography</a>
                    <a href="#" class="item channel_item">Health & Fitness</a>
                    <a href="#" class="item channel_item">Music</a>
                    <a href="#" class="item channel_item">Teaching & Academics</a>
                </div>
            </div>
        </div>
    </div> -->
    <!-- <div class="search120">
        <div class="ui search">
          <div class="ui left icon input swdh10">
            <input class="prompt srch10" type="text" placeholder="Search for Tuts Videos, Tutors, Tests and more..">
            <i class='uil uil-search-alt icon icon1'></i>
          </div>
        </div>
    </div> -->
    
    <div class="header_right">
        {% if user %}
        <ul>
            <li>
                <a href="{% url 'home:create_new_course' %}" class="upload_btn" title="Create New Course">Create New Course</a>
            </li>
            
            <li class="ui dropdown">
                <a href="#" class="option_links" title="Messages"><i class='uil uil-envelope-alt'></i><span class="noti_count">3</span></a>
                <div class="menu dropdown_ms">
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-6.jpg' %}" alt="">
                            <div class="pd_content">
                                <h6>Zoena Singh</h6>
                                <p>Hi! Sir, How are you. I ask you one thing please explain it this video price.</p>
                                <span class="nm_time">2 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-5.jpg' %}" alt="">
                            <div class="pd_content">
                                <h6>Joy Dua</h6>
                                <p>Hello, I paid you video tutorial but did not play error 404.</p>
                                <span class="nm_time">10 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-8.jpg' %}" alt="">
                            <div class="pd_content">
                                <h6>Jass</h6>
                                <p>Thanks Sir, Such a nice video.</p>
                                <span class="nm_time">25 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a class="vbm_btn" href="instructor_messages.html">View All <i class='uil uil-arrow-right'></i></a>
                </div>
            </li>
            <li class="ui dropdown">
                <a href="#" class="option_links" title="Notifications"><i class='uil uil-bell'></i><span class="noti_count">3</span></a>
                <div class="menu dropdown_mn">
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-1.jpg' %}" alt="">
                            <div class="pd_content">
                                <h6>Rock William</h6>
                                <p>Like Your Comment On Video <strong>How to create sidebar menu</strong>.</p>
                                <span class="nm_time">2 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-2.jpg' %}" alt="">
                            <div class="pd_content">
                                <h6>Jassica Smith</h6>
                                <p>Added New Review In Video <strong>Full Stack PHP Developer</strong>.</p>
                                <span class="nm_time">12 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a href="#" class="channel_my item">
                        <div class="profile_link">
                            <img src="{% static 'home/images/left-imgs/img-9.jpg' %}" alt="">
                            <div class="pd_content">
                                <p> Your Membership Approved <strong>Upload Video</strong>.</p>
                                <span class="nm_time">20 min ago</span>
                            </div>							
                        </div>							
                    </a>
                    <a class="vbm_btn" href="instructor_notifications.html">View All <i class='uil uil-arrow-right'></i></a>
                </div>
            </li>
            
            <li class="ui dropdown">
                <a href="#" class="opts_account" title="Account">
                    <img src="{{photo_url}}" alt="">
                </a>
                
                <div class="menu dropdown_account">
                    <div class="channel_my">
                        <div class="profile_link">
                            <img src="{{photo_url}}" alt="">
                            <div class="pd_content">
                                <div class="rhte85">
                                    <h6>{{fullname}}</h6>
                                    <div class="mef78" title="Verify">
                                        <i class='uil uil-check-circle'></i>
                                    </div>
                                </div>
                                <span>{{email}}</span>
                            </div>							
                        </div>
                        <a href="my_instructor_profile_view.html" class="dp_link_12">View Instructor Profile</a>						
                    </div>
                    <div class="night_mode_switch__btn">
                        <a href="#" id="night-mode" class="btn-night-mode">
                            <i class="uil uil-moon"></i> Night mode
                            <span class="btn-night-mode-switch">
                                <span class="uk-switch-button"></span>
                            </span>
                        </a>
                    </div>
                    <a href="{% url 'home:instructor_dashboard' %}" class="item channel_item">Cursus dashboard</a>						
                    <a href="{% url 'home:logout' %}" class="item channel_item">Sign Out</a>
                </div>
            </li>
            {% else %}
            <ul>
                <li>
                    <a href="{% url 'home:signup' %}" class="upload_btn" title="signup">Sign up</a>
                
                    <a href="{% url 'home:signin' %}" class="upload_btn" title="signin">Log In</a>
                </li>
            </ul>
            
            {% endif %}

        </ul>
    </div>
</header>

home/templates/home/instructor_sidenav.html
<nav class="vertical_nav">
    <div class="left_section menu_left" id="js-menu" >
        <div class="left_section">
            <br>
            <ul>
                <li class="menu--item">
                    <a href="{% url 'home:instructor_dashboard' %}" class="menu--link {{dashboard_active}}" title="Dashboard">
                        <i class="uil uil-apps menu--icon"></i>
                        <span class="menu--label">Dashboard</span>
                    </a>
                </li>
                <li class="menu--item">
                    <a href="{% url 'home:create_new_course' %}" class="menu--link {{course_active}}" title="Create Course">
                        <i class='uil uil-plus-circle menu--icon'></i>
                        <span class="menu--label">Create Course</span>
                    </a>
                </li>
                <li class="menu--item">
                    <a href="instructor_messages.html" class="menu--link {{messages_active}}" title="Messages">
                        <i class='uil uil-comments menu--icon'></i>
                        <span class="menu--label">Messages</span>
                    </a>
                </li>
                <li class="menu--item">
                    <a href="instructor_messages.html" class="menu--link {{quiz_active}}" title="Quiz Result">
                        <i class='uil uil-comments menu--icon'></i>
                        <span class="menu--label">Quiz & Result</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="left_section pt-2">
            <ul>
                <li class="menu--item">
                    <a href="setting.html" class="menu--link {{settings_active}}" title="Setting">
                        <i class='uil uil-cog menu--icon'></i>
                        <span class="menu--label">Settings</span>
                    </a>
                </li>
                <li class="menu--item">
                    <a href="feedback.html" class="menu--link {{feedback_active}}" title="Send Feedback">
                        <i class='uil uil-comment-alt-exclamation menu--icon'></i>
                        <span class="menu--label">Send Feedback</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

home/templates/home/sign_in.html
{% load static %}
{% include 'home/base.html' %}

<div class="sign_in_up_bg">
    <div class="container">
        <div class="row justify-content-lg-center justify-content-md-center">
            <div class="col-lg-12">
                <div class="main_logo25" id="logo">
                    <a href="index.html"><img src="images/logo.svg" alt=""></a>
                    <a href="index.html"><img class="logo-inverse" src="images/ct_logo.svg" alt=""></a>
                </div>
            </div>
        
            <div class="col-lg-6 col-md-8">
                <div class="sign_form">
                    <h2>Welcome Back</h2>
                    <p>Log In to Your Edututs+ Account!</p>
                    <!-- <button class="social_lnk_btn color_btn_fb"><i class="uil uil-facebook-f"></i>Continue with Facebook</button>
                    <button class="social_lnk_btn mt-15 color_btn_tw"><i class="uil uil-twitter"></i>Continue with Twitter</button>
                    <button class="social_lnk_btn mt-15 color_btn_go"><i class="uil uil-google"></i>Continue with Google</button> -->
                    <form action="{% url 'home:signin' %}" method="POST">
                        {% csrf_token %}
                        <div class="ui search focus mt-15">
                            <div class="ui left icon input swdh11 swdh19">
                                <input class="prompt srch_explore" type="email" name="emailaddress"  id="id_email" required="" maxlength="64" placeholder="Email Address">															
                                <i class="uil uil-envelope icon icon2"></i>
                            </div>
                        </div>
                        <div class="ui search focus mt-15">
                            <div class="ui left icon input swdh11 swdh19">
                                <input class="prompt srch_explore" type="password" name="password"  id="id_password" required="" maxlength="64" placeholder="Password">
                                <i class="uil uil-key-skeleton-alt icon icon2"></i>
                            </div>
                        </div>
                        <div class="ui form mt-30 checkbox_sign">
                            <div class="inline field">
                                <div class="ui checkbox mncheck">
                                    <input type="checkbox" tabindex="0" class="hidden">
                                    <label>Remember Me</label>
                                </div>
                            </div>
                        </div>
                        <button class="login-btn" type="submit">Sign In</button>
                    </form>
                    <p class="sgntrm145">Or <a href="forgot_password.html">Forgot Password</a>.</p>
                    <p class="mb-0 mt-30 hvsng145">Don't have an account? <a href="{% url 'home:signup' %}">Sign Up</a></p>
                </div>
                <div class="sign_footer"><img src="images/sign_logo.png" alt="">© 2020 <strong>Cursus</strong>. All Rights Reserved.</div>
            </div>				
        </div>				
    </div>				
</div>

home/templates/home/sign_up.html
{% load static %}
{% include 'home/base.html' %}

<div class="sign_in_up_bg">
    <div class="container">
        <div class="row justify-content-lg-center justify-content-md-center">
            <div class="col-lg-12">
                <div class="main_logo25" id="logo">
                    <a href="{% url 'home:landing' %}"><img src="{% static 'home/images/logo.svg' %}" alt=""></a>
                    <a href="{% url 'home:landing' %}"><img class="logo-inverse" src="{% static 'home/images/ct_logo.svg' %}" alt=""></a>
                </div>
            </div>
        
            <div class="col-lg-6 col-md-8">
                <div class="sign_form">
                    <h2>Welcome to Edututs+</h2>
                    <p>Sign Up and Start Learning!</p>
                    <form action="{% url 'home:signup' %}" method="POST">
                        {% csrf_token %}
                        <div class="ui search focus">
                            <div class="ui left icon input swdh11 swdh19">
                                <i class="uil uil-user icon icon2"></i>
                                <input class="prompt srch_explore" type="text" name="fullname"  id="id_fullname" required="" maxlength="64" placeholder="Full Name">															
                            </div>
                        </div>
                        <div class="ui search focus mt-15">
                            <div class="ui left icon input swdh11 swdh19">
                                <i class="uil uil-envelope icon icon2"></i>
                                <input class="prompt srch_explore" type="email" name="emailaddress"  id="id_email" required="" maxlength="64" placeholder="Email Address">															
                            </div>
                        </div>
                        <div class="ui search focus mt-15">
                            <div class="ui left icon input swdh11 swdh19">
                                <i class="uil uil-key-skeleton-alt icon icon2"></i>
                                <input class="prompt srch_explore" type="password" name="password"  id="id_password" required="" maxlength="64" placeholder="Password">															
                            </div>
                        </div>
                        <div class="ui search focus mt-15">
                            <div class="ui left icon input swdh11 swdh19">
                                <i class="uil uil-key-skeleton-alt icon icon2"></i>
                                <input class="prompt srch_explore" type="text" name="url"  id="id_url" required="" maxlength="64" placeholder="Photo URL">															
                            </div>
                        </div>
                        
                        <button class="login-btn" type="submit">Next</button>
                    </form>
                    <p class="sgntrm145">By signing up, you agree to our <a href="terms_of_use.html">Terms of Use</a> and <a href="terms_of_use.html">Privacy Policy</a>.</p>
                    <p class="mb-0 mt-30">Already have an account? <a href="{% url 'home:signin' %}">Log In</a></p>
                </div>
                <div class="sign_footer"><img src="{% static 'home/images/sign_logo.png' %}" alt="">© 2020 <strong>Cursus</strong>. All Rights Reserved.</div>
            </div>				
        </div>				
    </div>				
</div>

home/templates/platform/platform.html
{% load static %}
{% include 'home/header.html' %}
{% include 'home/instructor_sidenav.html' %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
#slide {
    color: black;
    display: block;
    height: 100%;
    line-height: 40px;
    text-decoration: none;
    width: 100%;
    text-align: center;
}
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: -33.5%;
  top: 60px;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
}

/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 5px;
  border: 1px solid #888;
  width: 30%;
}

/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}
</style>
</head>
<body>
  <div class="wrapper">
    <div class="sa4d25">
      <div class="container">


        here will be the mapping part <br>

        <button id="myBtn">Add slide</button> <br><br><br><br><br>

        <div id="myModal" class="modal wrapper">
          <div class="modal-content">
            <span class="close">&times;</span>
            <p>menu to choose type of slide (ex: long lesson, short lesson, quiz type1, etc)</p>
            <button class='close'>add</button>
          </div>
        </div>

        slides already added:- <br><br>

         <div style="width:130px; height:130px; background-color:white">
           <a id="slide" href="{% url 'home:studio' %}">Slide 1</a>
         </div>
         <br>
         <div style="width:130px; height:130px; background-color:white">
           <a id="slide" href="{% url 'home:studio' %}">Slide 2</a>
         </div>


      </div>
    </div>
  </div>

<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>

home/templates/studio/studio.html
{% load static %}
{% include 'home/header.html' %}
{% include 'home/instructor_sidenav.html' %}

<div class="wrapper">
  <div class="sa4d25">
    <div class="container">
      This is studio !!
    </div>
  </div>
</div>